version: "3.8"

services:
  faucet:
    container_name: celestia-discord-faucet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
